#use_frameworks!

platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
plugin 'cocoapods-repo-svn', :sources => ['https://10.7.12.91/repo/EHDiOS/trunk/EHDSpecRepo']

target 'Demo' do

  pod 'TFTestKit/Base'
  pod 'TFBaseObject', :path => '../'

end

target 'DemoTests' do

  pod 'TFTestKit/Base'
  pod 'TFBaseObject', :path => '../'

end