# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

target 'HSKVO' do

pod 'KVOController', :inhibit_warnings => true
pod 'SVProgressHUD', :inhibit_warnings => true

end

target 'HSKVOTests' do

pod 'KVOController', :inhibit_warnings => true

end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'DEFINE_CLOUD_HOSPITAL=1']
        end
    end
end

