
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

plugin 'cocoapods-repo-svn', :sources => [
    'https://10.7.12.91/repo/EHDiOS/trunk/EHDSpecRepo'
]

target 'TFLoadingView' do

pod 'TFLoadingView', :path => '../'

end
